config/routes.rb
Spotlight::Import::InternetArchive::Engine.routes.draw do

  resources :resources, only: [:new, :create]


end

app/models/spotlight/import/internet_archive/resource.rb
require 'faraday'
require 'faraday_middleware'

module Spotlight::Import::InternetArchive
  class Resource < ActiveRecord::Base
    belongs_to :solr_document
    serialize :data, Hash

    before_save do
      harvest! if url_changed?
    end

    after_save if: :data_changed? do
      index!
      self.update_columns indexed_at: Time.current
    end

    def index!
      Blacklight.solr.add solr_doc
    end

    def solr_doc
      h = { 
        id: solr_doc_id,
        spotlight_import_internet_archive_id_isi: id
      }

      h.merge! opengraph_properties

      h.merge! metadata_properties
    end

    def solr_doc_id
      url.split("/").last.parameterize
    end

    def harvest!
      response = Faraday.get url
      data[:raw_body] = response.body
      fetch_metadata!
    end

    def body
      @body ||= Nokogiri::HTML.parse data[:raw_body]
    end

    def opengraph
      @opengraph ||= begin
        page = Hash.new

        body.css('meta').select { |m| m.attribute('property') }.each do |m|
          page[m.attribute('property').to_s.parameterize("_")] = m.attribute('content').to_s
        end

        page
      end
    end

    def opengraph_properties
      opengraph.map do |k,v|
        ["#{k}_tesim", v]
      end.to_h
    end

    def metadata
      if data[:metadata].nil?
        fetch_metadata!
      end

      @metadata ||= Nokogiri::XML.parse data[:metadata]
    end

    def metadata_properties
      metadata.xpath('//*').map do |node|
        ["#{node.name}_tesim", node.text]
      end.to_h
    end

    def fetch_metadata!
      data[:metadata] = begin
        href = body.css('.fileFormats').select do |x| 
          x.at_css('.ttlHeader').text == "Information"
        end.first.css('a').select do |a|
          a.attribute("href").text.ends_with? "_meta.xml"
        end.first.attribute("href").text

        conn = Faraday.new url: 'https://archive.org' do|b|
          b.use FaradayMiddleware::FollowRedirects
          b.adapter Faraday.default_adapter
        end

        response = conn.get href
        response.body
      end
    end

  end
end

app/controllers/spotlight/import/application_controller.rb
require 'spotlight/import/internet_archive'

module Spotlight::Import::InternetArchive
  # Inherit from the host app's ApplicationController
  # This will configure e.g. the layout used by the host
  class ApplicationController < ::ApplicationController

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to main_app.root_url, :alert => exception.message
    end

  end
end

app/controllers/spotlight/import/internet_archive/resources_controller.rb
require_dependency "spotlight/import/internet_archive/application_controller"

module Spotlight::Import::InternetArchive
  class ResourcesController < ApplicationController
  
    # GET /resources/new
    # GET /resources/new.json
    def new
      @resource = Resource.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @resource }
      end
    end

    # POST /resources
    # POST /resources.json
    def create
      @resource = Resource.new(params[:resource])
  
      respond_to do |format|
        if @resource.save
          format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
          format.json { render json: @resource, status: :created, location: @resource }
        else
          format.html { render action: "new" }
          format.json { render json: @resource.errors, status: :unprocessable_entity }
        end
      end
    end

  end
end

app/helpers/spotlight/import/internet_archive/resources_helper.rb
module Spotlight::Import::InternetArchive
  module ResourcesHelper
  end
end

app/views/spotlight/import/internet_archive/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :indexed_at %><br />
    <%= f.datetime_select :indexed_at %>
  </div>
  <div class="field">
    <%= f.label :solr_document_id %><br />
    <%= f.text_field :solr_document_id %>
  </div>
  <div class="field">
    <%= f.label :metadata %><br />
    <%= f.text_area :metadata %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spotlight/import/internet_archive/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>